---
- name: Package Install
  hosts: db
  become: yes
  gather_facts: no
  tasks:

    - name: Insall memcached Package
      yum: name=memcached state=latest   
      tags:
        - t1

    - name: Insall httpd Package
      yum: name=httpd state=latest   
      tags:
        - t2
...
